### ISSUE TITLE
How would you like to manage different languages?

### ISSUE THREAD

**Issue by InteractiveNinja** [RickDB/PlexAniSync-Custom-Mappings#52]
I have added some German synonyms to some shows that did not match on my German Plex instance in PR #46.
I have added them to the `series-tvdb.en.yaml`, but it feels like the wrong approach for shows that are not matched in German, but perfectly fine in English. 

What are your thoughts on different language synonyms in this project? Should they be added to the series-tvdb.*en*.yaml?

Especially because I already have another show in my fork that is not mapped to German, so I thought I'd ask again if this is the correct way to go before I create another PR.

**Comment by reconman** [comment]
I don't think languages other than English and the native language should be added, otherwise we'd have 200 TVDB files and 200 TMDB files. If you add it to the tvdb.en one, we'd have 200 synonyms per show.

So I think you should keep the German titles in your local files.

**Comment by Soitora** [comment]
I'd say, you can PR a `series-tvdb.de.yaml` if you want, but it probably will end up being unmaintained if you yourself don't maintain it

No other languages than English + Native should exist in the default `en.yaml` files

**Comment by InteractiveNinja** [comment]
Okay, thanks for the clear up
