### ISSUE TITLE
Sorter and Validator

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync-Custom-Mappings#64]
Using the Sort.py and Validate.py files I have noticed two things.

1. `validate.py` requires `custom_mappings_schema.json`, but it needs to be local in the same folder, but it's not on the `.gitignore`
2. `sort.py` changes all my files to `CRLF`, it doesn't enforce the currently used `LF`

**Comment by reconman** [comment]
2. shouldn't be an issue if you have auto-CRLF enabled, which is Git default. Git should convert all files to LF when staging them.

**Comment by Soitora** [comment]
Auto-CRLF has various issue, thus I have that set to `false` with `eol=lf` set.

Not a fan of magic/invisible actions happening, would prefer them to be explicit all the way through

**Comment by reconman** [comment]
The problem with always converting to LF during sort is that people who use Windows Notepad for editing will see everything on 1 line afterwards.

**Comment by Soitora** [comment]
> The problem with always converting to LF during sort is that people who use Windows Notepad for editing will see everything on 1 line afterwards.

Iirc that was fixed years ago, and Notepad now respects Line Endings by looking at the symbol used

**Comment by Soitora** [comment]
Closed by #80
